		
INSERT INTO Languages(Code,Name) VALUES ('AB',N'Аҧсуа Бызшәа, Аҧсшәа')
INSERT INTO Languages(Code,Name) VALUES ('AA',N'Afaraf')
INSERT INTO Languages(Code,Name) VALUES ('AF',N'Afrikaans')
INSERT INTO Languages(Code,Name) VALUES ('AK',N'Akan')
INSERT INTO Languages(Code,Name) VALUES ('SQ',N'Shqip')
INSERT INTO Languages(Code,Name) VALUES ('AM',N'አማርኛ')
INSERT INTO Languages(Code,Name) VALUES ('AR',N'العربية')
INSERT INTO Languages(Code,Name) VALUES ('AN',N'Aragonés')
INSERT INTO Languages(Code,Name) VALUES ('HY',N'Հայերեն')
INSERT INTO Languages(Code,Name) VALUES ('AS',N'অসমীয়া')
INSERT INTO Languages(Code,Name) VALUES ('AV',N'Авар Мацӏ, Магӏарул Мацӏ')
INSERT INTO Languages(Code,Name) VALUES ('AE',N'Avesta')
INSERT INTO Languages(Code,Name) VALUES ('AY',N'Aymar Aru')
INSERT INTO Languages(Code,Name) VALUES ('AZ',N'Azərbaycan Dili')
INSERT INTO Languages(Code,Name) VALUES ('BM',N'Bamanankan')
INSERT INTO Languages(Code,Name) VALUES ('BA',N'Башҡорт Теле')
INSERT INTO Languages(Code,Name) VALUES ('EU',N'Euskara, Euskera')
INSERT INTO Languages(Code,Name) VALUES ('BE',N'Беларуская Мова')
INSERT INTO Languages(Code,Name) VALUES ('BN',N'বাংলা')
INSERT INTO Languages(Code,Name) VALUES ('BH',N'भोजपुरी')
INSERT INTO Languages(Code,Name) VALUES ('BI',N'Bislama')
INSERT INTO Languages(Code,Name) VALUES ('BS',N'Bosanski Jezik')
INSERT INTO Languages(Code,Name) VALUES ('BR',N'Brezhoneg')
INSERT INTO Languages(Code,Name) VALUES ('BG',N'Български Език')
INSERT INTO Languages(Code,Name) VALUES ('MY',N'ဗမာစာ')
INSERT INTO Languages(Code,Name) VALUES ('CA',N'Català, Valencià')
INSERT INTO Languages(Code,Name) VALUES ('CH',N'Chamoru')
INSERT INTO Languages(Code,Name) VALUES ('CE',N'Нохчийн Мотт')
INSERT INTO Languages(Code,Name) VALUES ('NY',N'Chicheŵa, Chinyanja')
INSERT INTO Languages(Code,Name) VALUES ('ZH',N'中文(Zhōngwén), 汉语, 漢語')
INSERT INTO Languages(Code,Name) VALUES ('CV',N'Чӑваш Чӗлхи')
INSERT INTO Languages(Code,Name) VALUES ('KW',N'Kernewek')
INSERT INTO Languages(Code,Name) VALUES ('CO',N'Corsu')
INSERT INTO Languages(Code,Name) VALUES ('CR',N'ᓀᐦᐃᔭᐍᐏᐣ')
INSERT INTO Languages(Code,Name) VALUES ('HR',N'Hrvatski Jezik')
INSERT INTO Languages(Code,Name) VALUES ('CS',N'Čeština')
INSERT INTO Languages(Code,Name) VALUES ('DA',N'Dansk')
INSERT INTO Languages(Code,Name) VALUES ('DV',N'ދިވެހި')
INSERT INTO Languages(Code,Name) VALUES ('NL',N'Nederlands, Vlaams')
INSERT INTO Languages(Code,Name) VALUES ('DZ',N'རྫོང་ཁ')
INSERT INTO Languages(Code,Name) VALUES ('EN',N'English')
INSERT INTO Languages(Code,Name) VALUES ('EO',N'Esperanto')
INSERT INTO Languages(Code,Name) VALUES ('ET',N'Eesti')
INSERT INTO Languages(Code,Name) VALUES ('EE',N'Eʋegbe')
INSERT INTO Languages(Code,Name) VALUES ('FO',N'Føroyskt')
INSERT INTO Languages(Code,Name) VALUES ('FJ',N'Vosa Vakaviti')
INSERT INTO Languages(Code,Name) VALUES ('FI',N'Suomi')
INSERT INTO Languages(Code,Name) VALUES ('FR',N'Français')
INSERT INTO Languages(Code,Name) VALUES ('FF',N'Fulfulde, Pulaar, Pular')
INSERT INTO Languages(Code,Name) VALUES ('GL',N'Galego')
INSERT INTO Languages(Code,Name) VALUES ('KA',N'ქართული')
INSERT INTO Languages(Code,Name) VALUES ('DE',N'Deutsch')
INSERT INTO Languages(Code,Name) VALUES ('EL',N'Ελληνικά')
INSERT INTO Languages(Code,Name) VALUES ('GN',N'Avañe''Ẽ')
INSERT INTO Languages(Code,Name) VALUES ('GU',N'ગુજરાતી')
INSERT INTO Languages(Code,Name) VALUES ('HT',N'Kreyòl Ayisyen')
INSERT INTO Languages(Code,Name) VALUES ('HA',N'(Hausa) هَوُسَ')
INSERT INTO Languages(Code,Name) VALUES ('HE',N'עברית')
INSERT INTO Languages(Code,Name) VALUES ('HZ',N'Otjiherero')
INSERT INTO Languages(Code,Name) VALUES ('HI',N'हिन्दी, हिंदी')
INSERT INTO Languages(Code,Name) VALUES ('HO',N'Hiri Motu')
INSERT INTO Languages(Code,Name) VALUES ('HU',N'Magyar')
INSERT INTO Languages(Code,Name) VALUES ('IA',N'Interlingua')
INSERT INTO Languages(Code,Name) VALUES ('ID',N'Bahasa Indonesia')
INSERT INTO Languages(Code,Name) VALUES ('GA',N'Gaeilge')
INSERT INTO Languages(Code,Name) VALUES ('IG',N'Asụsụ Igbo')
INSERT INTO Languages(Code,Name) VALUES ('IK',N'Iñupiaq, Iñupiatun')
INSERT INTO Languages(Code,Name) VALUES ('IO',N'Ido')
INSERT INTO Languages(Code,Name) VALUES ('IS',N'Íslenska')
INSERT INTO Languages(Code,Name) VALUES ('IT',N'Italiano')
INSERT INTO Languages(Code,Name) VALUES ('IU',N'ᐃᓄᒃᑎᑐᑦ')
INSERT INTO Languages(Code,Name) VALUES ('JA',N'日本語 (にほんご)')
INSERT INTO Languages(Code,Name) VALUES ('JV',N'ꦧꦱꦗꦮ, Basa Jawa')
INSERT INTO Languages(Code,Name) VALUES ('KL',N'Kalaallisut')
INSERT INTO Languages(Code,Name) VALUES ('KN',N'ಕನ್ನಡ')
INSERT INTO Languages(Code,Name) VALUES ('KR',N'Kanuri')
INSERT INTO Languages(Code,Name) VALUES ('KS',N'कश्मीरी, كشميري‎')
INSERT INTO Languages(Code,Name) VALUES ('KK',N'Қазақ Тілі')
INSERT INTO Languages(Code,Name) VALUES ('KM',N'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ')
INSERT INTO Languages(Code,Name) VALUES ('KI',N'Gĩkũyũ')
INSERT INTO Languages(Code,Name) VALUES ('RW',N'Ikinyarwanda')
INSERT INTO Languages(Code,Name) VALUES ('KY',N'Кыргызча, Кыргыз Тили')
INSERT INTO Languages(Code,Name) VALUES ('KV',N'Коми Кыв')
INSERT INTO Languages(Code,Name) VALUES ('KG',N'Kikongo')
INSERT INTO Languages(Code,Name) VALUES ('KO',N'한국어')
INSERT INTO Languages(Code,Name) VALUES ('KU',N'Kurdî, كوردی‎')
INSERT INTO Languages(Code,Name) VALUES ('KJ',N'Kuanyama')
INSERT INTO Languages(Code,Name) VALUES ('LA',N'Latine')
INSERT INTO Languages(Code,Name) VALUES ('LB',N'Lëtzebuergesch')
INSERT INTO Languages(Code,Name) VALUES ('LG',N'Luganda')
INSERT INTO Languages(Code,Name) VALUES ('LI',N'Limburgs')
INSERT INTO Languages(Code,Name) VALUES ('LN',N'Lingála')
INSERT INTO Languages(Code,Name) VALUES ('LO',N'ພາສາລາວ')
INSERT INTO Languages(Code,Name) VALUES ('LT',N'Lietuvių Kalba')
INSERT INTO Languages(Code,Name) VALUES ('LU',N'Kiluba')
INSERT INTO Languages(Code,Name) VALUES ('LV',N'Latviešu Valoda')
INSERT INTO Languages(Code,Name) VALUES ('GV',N'Gaelg, Gailck')
INSERT INTO Languages(Code,Name) VALUES ('MK',N'Македонски Јазик')
INSERT INTO Languages(Code,Name) VALUES ('MG',N'Fiteny Malagasy')
INSERT INTO Languages(Code,Name) VALUES ('MS',N'Bahasa Melayu, بهاس ملايو‎')
INSERT INTO Languages(Code,Name) VALUES ('ML',N'മലയാളം')
INSERT INTO Languages(Code,Name) VALUES ('MT',N'Malti')
INSERT INTO Languages(Code,Name) VALUES ('MI',N'Te Reo Māori')
INSERT INTO Languages(Code,Name) VALUES ('MR',N'मराठी')
INSERT INTO Languages(Code,Name) VALUES ('MH',N'Kajin M̧Ajeļ')
INSERT INTO Languages(Code,Name) VALUES ('MN',N'Монгол Хэл')
INSERT INTO Languages(Code,Name) VALUES ('NA',N'Dorerin Naoero')
INSERT INTO Languages(Code,Name) VALUES ('NV',N'Diné Bizaad')
INSERT INTO Languages(Code,Name) VALUES ('ND',N'Isindebele')
INSERT INTO Languages(Code,Name) VALUES ('NE',N'नेपाली')
INSERT INTO Languages(Code,Name) VALUES ('NG',N'Owambo')
INSERT INTO Languages(Code,Name) VALUES ('NB',N'Norsk Bokmål')
INSERT INTO Languages(Code,Name) VALUES ('NN',N'Norsk Nynorsk')
INSERT INTO Languages(Code,Name) VALUES ('NO',N'Norsk')
INSERT INTO Languages(Code,Name) VALUES ('II',N'ꆈꌠ꒿ Nuosuhxop')
INSERT INTO Languages(Code,Name) VALUES ('NR',N'Isindebele')
INSERT INTO Languages(Code,Name) VALUES ('OC',N'Occitan, Lenga D''Òc')
INSERT INTO Languages(Code,Name) VALUES ('OJ',N'ᐊᓂᔑᓈᐯᒧᐎᓐ')
INSERT INTO Languages(Code,Name) VALUES ('CU',N'Ѩзыкъ Словѣньскъ')
INSERT INTO Languages(Code,Name) VALUES ('OM',N'Afaan Oromoo')
INSERT INTO Languages(Code,Name) VALUES ('OR',N'ଓଡ଼ିଆ')
INSERT INTO Languages(Code,Name) VALUES ('OS',N'Ирон Æвзаг')
INSERT INTO Languages(Code,Name) VALUES ('PA',N'ਪੰਜਾਬੀ')
INSERT INTO Languages(Code,Name) VALUES ('PI',N'पाऴि')
INSERT INTO Languages(Code,Name) VALUES ('FA',N'فارسی')
INSERT INTO Languages(Code,Name) VALUES ('PL',N'Polszczyzna')
INSERT INTO Languages(Code,Name) VALUES ('PS',N'پښتو')
INSERT INTO Languages(Code,Name) VALUES ('PT',N'Português')
INSERT INTO Languages(Code,Name) VALUES ('QU',N'Runa Simi, Kichwa')
INSERT INTO Languages(Code,Name) VALUES ('RM',N'Rumantsch Grischun')
INSERT INTO Languages(Code,Name) VALUES ('RN',N'Ikirundi')
INSERT INTO Languages(Code,Name) VALUES ('RO',N'Română')
INSERT INTO Languages(Code,Name) VALUES ('RU',N'Русский')
INSERT INTO Languages(Code,Name) VALUES ('SA',N'संस्कृतम्')
INSERT INTO Languages(Code,Name) VALUES ('SC',N'Sardu')
INSERT INTO Languages(Code,Name) VALUES ('SD',N'सिन्धी, سنڌي، سندھی‎')
INSERT INTO Languages(Code,Name) VALUES ('SE',N'Davvisámegiella')
INSERT INTO Languages(Code,Name) VALUES ('SM',N'Gagana Fa''A Samoa')
INSERT INTO Languages(Code,Name) VALUES ('SG',N'Yângâ Tî Sängö')
INSERT INTO Languages(Code,Name) VALUES ('SR',N'Српски Језик')
INSERT INTO Languages(Code,Name) VALUES ('GD',N'Gàidhlig')
INSERT INTO Languages(Code,Name) VALUES ('SN',N'Chishona')
INSERT INTO Languages(Code,Name) VALUES ('SI',N'සිංහල')
INSERT INTO Languages(Code,Name) VALUES ('SK',N'Slovenčina')
INSERT INTO Languages(Code,Name) VALUES ('SL',N'Slovenščina')
INSERT INTO Languages(Code,Name) VALUES ('SO',N'Soomaaliga')
INSERT INTO Languages(Code,Name) VALUES ('ST',N'Sesotho')
INSERT INTO Languages(Code,Name) VALUES ('ES',N'Español')
INSERT INTO Languages(Code,Name) VALUES ('SU',N'Basa Sunda')
INSERT INTO Languages(Code,Name) VALUES ('SW',N'Kiswahili')
INSERT INTO Languages(Code,Name) VALUES ('SS',N'Siswati')
INSERT INTO Languages(Code,Name) VALUES ('SV',N'Svenska')
INSERT INTO Languages(Code,Name) VALUES ('TA',N'தமிழ்')
INSERT INTO Languages(Code,Name) VALUES ('TE',N'తెలుగు')
INSERT INTO Languages(Code,Name) VALUES ('TG',N'Тоҷикӣ, Toçikī, تاجیکی‎')
INSERT INTO Languages(Code,Name) VALUES ('TH',N'ไทย')
INSERT INTO Languages(Code,Name) VALUES ('TI',N'ትግርኛ')
INSERT INTO Languages(Code,Name) VALUES ('BO',N'བོད་ཡིག')
INSERT INTO Languages(Code,Name) VALUES ('TK',N'Türkmen, Түркмен')
INSERT INTO Languages(Code,Name) VALUES ('TL',N'Wikang Tagalog')
INSERT INTO Languages(Code,Name) VALUES ('TN',N'Setswana')
INSERT INTO Languages(Code,Name) VALUES ('TO',N'Faka Tonga')
INSERT INTO Languages(Code,Name) VALUES ('TR',N'Türkçe')
INSERT INTO Languages(Code,Name) VALUES ('TS',N'Xitsonga')
INSERT INTO Languages(Code,Name) VALUES ('TT',N'Татар Теле, Tatar Tele')
INSERT INTO Languages(Code,Name) VALUES ('TW',N'Twi')
INSERT INTO Languages(Code,Name) VALUES ('TY',N'Reo Tahiti')
INSERT INTO Languages(Code,Name) VALUES ('UG',N'ئۇيغۇرچە‎Uyghurche')
INSERT INTO Languages(Code,Name) VALUES ('UK',N'Українська')
INSERT INTO Languages(Code,Name) VALUES ('UR',N'اردو')
INSERT INTO Languages(Code,Name) VALUES ('UZ',N'Oʻzbek, Ўзбек, أۇزبېك‎')
INSERT INTO Languages(Code,Name) VALUES ('VE',N'Tshivenḓa')
INSERT INTO Languages(Code,Name) VALUES ('VI',N'Tiếng Việt')
INSERT INTO Languages(Code,Name) VALUES ('VO',N'Volapük')
INSERT INTO Languages(Code,Name) VALUES ('WA',N'Walon')
INSERT INTO Languages(Code,Name) VALUES ('CY',N'Cymraeg')
INSERT INTO Languages(Code,Name) VALUES ('WO',N'Wollof')
INSERT INTO Languages(Code,Name) VALUES ('FY',N'Frysk')
INSERT INTO Languages(Code,Name) VALUES ('XH',N'Isixhosa')
INSERT INTO Languages(Code,Name) VALUES ('YI',N'ייִדיש')
INSERT INTO Languages(Code,Name) VALUES ('YO',N'Yorùbá')
INSERT INTO Languages(Code,Name) VALUES ('ZA',N'Saɯ Cueŋƅ, Saw Cuengh')
INSERT INTO Languages(Code,Name) VALUES ('ZU',N'Isizulu')
