//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address : IEntity
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> Is_DeliveryAddress { get; set; }
        public Nullable<bool> Is_BillingAddress { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public int Ua_Id { get; set; }
        public int Loc_Id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
