//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.DB
{
    using System;

    public partial class CompanyDetails2UserDetailsDbo : IEntity
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int CompanyDetailsId { get; set; }
        public int UserDetailsId { get; set; }

        public virtual CompanyDetailsDbo CompanyDetails { get; set; }
        public virtual UserDetailsDbo UserDetails { get; set; }
    }
}
