//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EBADOEntitiesTest : DbContext
    {
        public EBADOEntitiesTest(string connectionString) : base (connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDbo> AddressDbo { get; set; }
        public virtual DbSet<AttachmentDbo> AttachmentDbo { get; set; }
        public virtual DbSet<CategoryDbo> CategoryDbo { get; set; }
        public virtual DbSet<Category2CompanyDetailsDbo> Category2CompanyDetailsDbo { get; set; }
        public virtual DbSet<CompanyDetailDbo> CompanyDetailDbo { get; set; }
        public virtual DbSet<CompanyDetails2UserDetailsDbo> CompanyDetails2UserDetailsDbo { get; set; }
        public virtual DbSet<CompanyPermissionDbo> CompanyPermissionDbo { get; set; }
        public virtual DbSet<CompanyRoleDbo> CompanyRoleDbo { get; set; }
        public virtual DbSet<CompanyRole2CompanyPermissionDbo> CompanyRole2CompanyPermissionDbo { get; set; }
        public virtual DbSet<CompanyTypeDbo> CompanyTypeDbo { get; set; }
        public virtual DbSet<LocationDbo> LocationDbo { get; set; }
        public virtual DbSet<SubCategoryDbo> SubCategoryDbo { get; set; }
        public virtual DbSet<SubCategory2CompanyDetailsDbo> SubCategory2CompanyDetailsDbo { get; set; }
        public virtual DbSet<UserDetailDbo> UserDetailDbo { get; set; }
        public virtual DbSet<UserPermissionDbo> UserPermissionDbo { get; set; }
        public virtual DbSet<UserRoleDbo> UserRoleDbo { get; set; }
        public virtual DbSet<UserRole2UserPermissionDbo> UserRole2UserPermissionDbo { get; set; }
        public virtual DbSet<BatchAttachmentDbo> BatchAttachmentDbo { get; set; }
    }
}
