//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateDbo : IEntity
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string SkSubject { get; set; }
        public string SkBody { get; set; }
        public string CzSubject { get; set; }
        public string CzBody { get; set; }
        public string HuSubject { get; set; }
        public string HuBody { get; set; }
        public string EnSubject { get; set; }
        public string EnBody { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
