//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettingDbo : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSettingDbo()
        {
            this.UserDetails = new HashSet<UserDetailDbo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SearchRadius { get; set; }
        public bool SearchInSK { get; set; }
        public bool SearchInCZ { get; set; }
        public bool SearchInHU { get; set; }
        public bool NotifyCommentOnContribution { get; set; }
        public bool NotifyCommentOnAccount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetailDbo> UserDetails { get; set; }
    }
}
