//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string AccountTypeCompany {
            get {
                return ResourceManager.GetString("AccountTypeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string AccountTypeContractor {
            get {
                return ResourceManager.GetString("AccountTypeContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Employed.
        /// </summary>
        public static string AccountTypeSelfEmployed {
            get {
                return ResourceManager.GetString("AccountTypeSelfEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic account.
        /// </summary>
        public static string BasicAccount {
            get {
                return ResourceManager.GetString("BasicAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business area.
        /// </summary>
        public static string BusinessArea {
            get {
                return ResourceManager.GetString("BusinessArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company account.
        /// </summary>
        public static string CompanyAccount {
            get {
                return ResourceManager.GetString("CompanyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company information.
        /// </summary>
        public static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech republic.
        /// </summary>
        public static string CountryCZ {
            get {
                return ResourceManager.GetString("CountryCZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        public static string CountryHU {
            get {
                return ResourceManager.GetString("CountryHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string CountrySelect {
            get {
                return ResourceManager.GetString("CountrySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak Republic.
        /// </summary>
        public static string CountrySK {
            get {
                return ResourceManager.GetString("CountrySK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have a company number.
        /// </summary>
        public static string DontHaveCopanyNumber {
            get {
                return ResourceManager.GetString("DontHaveCopanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login information.
        /// </summary>
        public static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string PHCompanyName {
            get {
                return ResourceManager.GetString("PHCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company number*.
        /// </summary>
        public static string PHCompanyNumber {
            get {
                return ResourceManager.GetString("PHCompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail*.
        /// </summary>
        public static string PHEmail {
            get {
                return ResourceManager.GetString("PHEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name*.
        /// </summary>
        public static string PHFirstname {
            get {
                return ResourceManager.GetString("PHFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name*.
        /// </summary>
        public static string PHLastName {
            get {
                return ResourceManager.GetString("PHLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password*.
        /// </summary>
        public static string PHPassword {
            get {
                return ResourceManager.GetString("PHPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number*.
        /// </summary>
        public static string PHPhoneNumber {
            get {
                return ResourceManager.GetString("PHPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code*.
        /// </summary>
        public static string PHPostalCode {
            get {
                return ResourceManager.GetString("PHPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password*.
        /// </summary>
        public static string PHRepeatPassword {
            get {
                return ResourceManager.GetString("PHRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name*.
        /// </summary>
        public static string PHStreetName {
            get {
                return ResourceManager.GetString("PHStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street number*.
        /// </summary>
        public static string PHStreetNumber {
            get {
                return ResourceManager.GetString("PHStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PHTitle {
            get {
                return ResourceManager.GetString("PHTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string Register2 {
            get {
                return ResourceManager.GetString("Register2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
